# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudMusic
  
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'

end
